### ISSUE TITLE
是否具备可视化绘图的能力支持

### ISSUE THREAD

**Issue by Viyond** [JDEasyFlow/jd-easyflow#1]
请问下，除了采用配置文件的方式来定义flow，是否提供页面可视化的流程图绘制能力。

**Comment by liyuliang-zz** [comment]
有的。JDEasyFlow除了原生的json格式规范外，还支持BPMN格式规范（内部执行时会自动将BPMN格式翻译为原生json格式）。 
BPMN模块实现了BPMN规范的部分原语，基于bpmnjs组件提供了流程图绘制的能力，离线版本见：https://github.com/JDEasyFlow/jd-easyflow/blob/master/easyflow-flow-bpmn/BPMNDesigner.html ，相关js可集成到项目工程中。
