### ISSUE TITLE
BPMN To Json没开源吗

### ISSUE THREAD

**Issue by SoftwareKing** [JDEasyFlow/jd-easyflow#4]
<img width="1235" alt="image" src="https://github.com/JDEasyFlow/jd-easyflow/assets/6858857/d0a4b4a9-2cd9-4ff2-b4e7-699a895813b9">

**Comment by liyuliang-zz** [comment]
离线版本的BPMN设计器在查看转换后的JSON流程定义时，需要搭建一个后端服务接口，调用组件的BpmnConverter将bpmn格式转换为json格式并返回给前端。具体步骤为：
1、后端接口开发。参考代码如下(基于spring mvc)：
```
@Controller
public class Bpmn2JsonController {
     
    @CrossOrigin(origins = "*")
    @RequestMapping(value = "/public/ajax/bpmn2Json")
    @ResponseBody
    public Map<String, String> convert2Json2(String bpmnXmlData) {
        Map<String, String> result = new HashMap<>();
        String jsonData = BpmnConverter.convert(bpmnXmlData);
        result.put("resultData", jsonData);
        return result;
    } 
}
```
2、前端调用后端的接口地址配置。打开easyflow-flow-bpmn/BPMNDesigner.html将window.bpmn2JsonUrl = null;修改为以上接口暴露的地址，如```http://localhost:8080/public/ajax/bpmn2Json```
